server:
  port: ${GATEWAY_PORT:8080}

#---
# Logging
logging:
  level:
    com.processing.gateway: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.server.mvc: TRACE
    org.springframework.http.client: TRACE
    org.springframework.web.client: DEBUG
#  pattern:
#    console: %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

#---
# Actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always

# Gateway
gateway:
  downstream-services:
    urls:
      switch-url: http://switch:${SWITCH_PORT:8082}
      logger-url: http://logger:${LOGGER_PORT:8088}
      auth-url: http://authorization:${AUTH_PORT:8083}
      cards-url: http://card-management:${CARD_MGMT_PORT:8081}
