server:
  port: ${SERVER_PORT:${GATEWAY_PORT:8080}}

#---
# Logging
logging:
  level:
    com.processing.gateway: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.server.mvc: TRACE
    org.springframework.http.client: TRACE
    org.springframework.web.client: DEBUG
#  pattern:
#    console: %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

#---
# Actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
    health:
      show-details: always

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: switch
            uri: ${SWITCH_URL:http://localhost:8082}
            predicates:
              - Path=/api/transactions
              - Method=POST
            filters:
              - RewritePath=/api/transactions, /api/internal/route
          - id: logger
            uri: ${LOGGER_URL:http://localhost:8088}
            predicates:
              - Path=/api/transactions/search
          - id: dashboard
            uri: ${LOGGER_URL:http://localhost:8088}
            predicates:
              - Path=/api/dashboard/**
          - id: terminal
            uri: ${TERMINAL_SIM_URL:http://localhost:8085}
            predicates:
              - Path=/api/simulator/terminal/**
          - id: merchant
            uri: ${MERCHANT_SIM_URL:http://localhost:8086}
            predicates:
              - Path=/api/simulator/merchant/**
          - id: cards
            uri: ${CARD_MGMT_URL:http://localhost:8081}
            predicates:
              - Path=/api/cards/**

        # OpenApi endpoints
          - id: switch-docs
            uri: ${SWITCH_URL:http://localhost:8082}
            predicates:
              - Path=/switch-docs
              - Method=GET
            filters:
              - RewritePath=/switch-docs, /v3/api-docs
          - id: logger-docs
            uri: ${LOGGER_URL:http://localhost:8088}
            predicates:
              - Path=/logger-docs
              - Method=GET
            filters:
              - RewritePath=/logger-docs, /v3/api-docs
          - id: terminal-docs
            uri: ${TERMINAL_SIM_URL:http://localhost:8085}
            predicates:
              - Path=/terminal-docs
              - Method=GET
            filters:
              - RewritePath=/terminal-docs, /v3/api-docs
          - id: merchant-docs
            uri: ${MERCHANT_SIM_URL:http://localhost:8086}
            predicates:
              - Path=/merchant-docs
              - Method=GET
            filters:
              - RewritePath=/merchant-docs, /v3/api-docs
          - id: cards-docs
            uri: ${CARD_MGMT_URL:http://localhost:8081}
            predicates:
              - Path=/cards-docs
              - Method=GET
            filters:
              - RewritePath=/cards-docs, /v3/api-docs
  mvc:
    log-request-details: true
  endpoint:
    health:
      show-details: always



# Gateway
gateway:
  downstream-services:
    urls:
      switch-url: ${SWITCH_URL:http://localhost:8082}
      logger-url: ${LOGGER_URL:http://localhost:8088}
      auth-url: ${AUTH_URL:http://localhost:8083}
      cards-url: ${CARD_MGMT_URL:http://localhost:8081}
  rate-limit:
    transactions-per-second: ${TRANSACTIONS_RATE_LIMIT:100}
  open-api:
    url: ${GATEWAY_PUBLIC_URL:http://localhost:${GATEWAY_PORT:8080}}

#---
# Swagger
springdoc:
  swagger-ui:
    path: /docs
    urls:
      - name: Gateway
        url: /v3/api-docs
      - name: Switch
        url: /switch-docs
      - name: Transaction Logger
        url: /logger-docs
      - name: Terminal Simulator
        url: /terminal-docs
      - name: Merchant Acquirer
        url: /merchant-docs
      - name: Card Management
        url: /cards-docs
