spring.config.import=optional:file:.env[.properties]
server.port=${SERVER_PORT:8080}
# PostgreSQL
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.jakarta.persistence.lock.timeout=5000
# Logging
logging.level.com.processing=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=card-management
management.metrics.distribution.percentiles-histogram.[http.server.requests]=true
management.metrics.distribution.percentiles.[http.server.requests]=0.5,0.95,0.99
# Application
app.service-name=${SERVICE_NAME:card-management}
# Card Service
app.card-service.issuer-id=${ISSUER_ID:ZZZZZZ}
app.card-service.card-validity-period=${CARD_YTL:3}
# Card Service Defaults
app.card-service.defaults.page-offset=${DEFAULT_OFFSET:0}
app.card-service.defaults.page-limit=${DEFAULT_LIMIT:50}
app.card-service.defaults.currency-code=${DEFAULT_CURRENCY_CODE:643}
app.card-service.defaults.daily-limit=${DEFAULT_DAILY_LIMIT:15000000}
app.card-service.defaults.monthly-limit=${DEFAULT_MONTHLY_LIMIT:300000000}
app.card-service.default-balance=${DEFAULT_BALANCE:1000000}
# Generator
app.card-generator.min-balance=${MIN_BALANCE:1000000}
app.card-generator.max-balance=${MAX_BALANCE:50000000}
app.card-generator.min-daily-limit=${MIN_DAILY_LIMIT:5000000}
app.card-generator.max-daily-limit=${MAX_DAILY_LIMIT:30000000}
app.card-generator.currency-code=${CURRENCY_CODE:643}
app.card-generator.batch-size=${BATCH_SIZE:643}
